/* Auth Action */
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const RECIVED_LOGIN = "RECIVED_LOGIN";
export const FAILED_LOGIN = "FAILED_LOGIN";
export const RESET_LOGIN_REQUEST = "RESET_LOGIN_REQUEST";
export const HARD_LOGIN_RESET = "HARD_LOGIN_RESET";

/* Feeding Line Action */
export const REQUEST_FEEDING_LINE_LIST = "REQUEST_FEEDING_LINE_LIST";
export const RECEIVED_FEEDING_LINE_LIST = "RECEIVED_FEEDING_LINE_LIST";
export const FAILED_FEEDING_LINE_LIST = "FAILED_FEEDING_LINE_LIST";
export const REQUEST_FEEDING_LINE = "REQUEST_FEEDING_LINE";
export const RECEIVED_FEEDING_LINE = "RECEIVED_FEEDING_LINE";
export const FAILED_FEEDING_LINE = "FAILED_FEEDING_LINE";
export const RESET_FEEDING_LINE = "RESET_FEEDING_LINE";
export const SAVE_FEEDING_LINE_REQUEST = "SAVE_FEEDING_LINE_REQUEST";
export const SAVE_FEEDING_LINE_SUCCESS = "SAVE_FEEDING_LINE_SUCCESS";
export const SAVE_FEEDING_LINE_FAILED = "SAVE_FEEDING_LINE_FAILED";
export const DELETE_FEEDING_LINE_REQUEST = "DELETE_FEEDING_LINE_REQUEST";
export const DELETE_FEEDING_LINE_SUCCESS = "DELETE_FEEDING_LINE_SUCCESS";
export const DELETE_FEEDING_LINE_FAILED = "DELETE_FEEDING_LINE_FAILED";

/* Pulp Information Action */
export const REQUEST_PULP_INFORMATION_LIST = "REQUEST_PULP_INFORMATION_LIST";
export const RECEIVED_PULP_INFORMATION_LIST = "RECEIVED_PULP_INFORMATION_LIST";
export const FAILED_PULP_INFORMATION_LIST = "FAILED_PULP_INFORMATION_LIST";
export const REQUEST_PULP_INFORMATION = "REQUEST_PULP_INFORMATION";
export const RECEIVED_PULP_INFORMATION = "RECEIVED_PULP_INFORMATION";
export const FAILED_PULP_INFORMATION = "FAILED_PULP_INFORMATION";
export const RESET_PULP_INFORMATION = "RESET_PULP_INFORMATION";
export const SAVE_PULP_INFORMATION_REQUEST = "SAVE_PULP_INFORMATION_REQUEST";
export const SAVE_PULP_INFORMATION_SUCCESS = "SAVE_PULP_INFORMATION_SUCCESS";
export const SAVE_PULP_INFORMATION_FAILED = "SAVE_PULP_INFORMATION_FAILED";
export const DELETE_PULP_INFORMATION_REQUEST =
  "DELETE_PULP_INFORMATION_REQUEST";
export const DELETE_PULP_INFORMATION_SUCCESS =
  "DELETE_PULP_INFORMATION_SUCCESS";
export const DELETE_PULP_INFORMATION_FAILED = "DELETE_PULP_INFORMATION_FAILED";
