export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const RECIVED_LOGIN = "RECIVED_LOGIN";
export const FAILED_LOGIN = "FAILED_LOGIN";
export const RESET_LOGIN_REQUEST = "RESET_LOGIN_REQUEST";
export const HARD_LOGIN_RESET = "HARD_LOGIN_RESET";
